server:
  port: 8089

spring.datasource:
  url: jdbc:mysql://192.168.4.151:3306/icity?useUnicode=true&characterEncoding=utf-8
  username: root
  password: icityDB2018!@#
  driver-class-name: com.mysql.jdbc.Driver

spring.jpa.hibernate.ddl-auto: update


eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.4.152
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:8761/eureka/

cas:
  enabled: true
  prefixUrl: http://localhost:9000
  loginUrl: ${cas.prefixUrl}/login
  callbackUrl: http://localhost:${server.port}/callback
  logoutRedirect: http://localhost:${server.port}/swagger-ui.html

oauth2:
  enabled: false
  server: http://192.168.4.10
  baseUrl: ${oauth2.server}/api/reception-center
  clientId: public
  clientSecret: public
  accessTokenUri: ${oauth2.baseUrl}/oauth/token
  userAuthorizationUri: ${oauth2.baseUrl}/oauth/authorize
  profileUrl: ${oauth2.baseUrl}/member/who
  logoutUrl: ${oauth2.baseUrl}/member/logout
  logoutRedirect: ${oauth2.server}/auth_static/logout.html?redirect_uri=http://localhost:${server.port}/test&client_id=${oauth2.clientId}
  callbackUrl: http://localhost:${server.port}/callback

jwt:
  salt: ascs.tech

shiro:
  pathDefinitions:
    - /** = anon
 
 
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true