server:
  port: 8085

#spring.profiles.active: ns

spring.application.name: iform_test

info:
  app:
    name: ${spring.application.name}
    version: V0.7.1.0
    time: 2018年09月18日 13:55:11
  describe: 表单引擎
  home: /
  author: administrator

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.188
  client:
    serviceUrl:
      defaultZone: http://192.168.4.151:8761/eureka/

spring.datasource:
  url: jdbc:postgresql://192.168.4.151:5432/icity
  username: root
  password: icityDB2018!@#
  driver-class-name: org.postgresql.Driver

spring.jpa:
  hibernate.ddl-auto: update
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  properties.hibernate.temp.use_jdbc_metadata_defaults: false

#请求处理的超时时间
ribbon.ReadTimeout: 120000
#请求连接的超时时间
ribbon.ConnectTimeout: 120000

icity:
  iform:
    qrcode:
      base-url: http://192.168.4.152:8089
      name: 航天智慧cityworks
  dictionary:
    areaCode:
      id: 9fddec6151b14a04bfe21d80d7a4474b

spring.redis:
  database: 0
  host: 192.168.4.151
  port: 6379
  password:
  timeout: 5000ms

spring.rabbitmq:
  host: 192.168.4.151
  port: 5672
  username: guest
  password: guest

spring.cloud.stream.bindings.output.destination: iform 
spring.cloud.stream.bindings.inputIFlow.destination: iflow

logging.level:
  org.hibernate.SQL: WARN
  org.hibernate.type.descriptor.sql.BasicBinder: WARN
  org.springframework.cloud.stream: WARN

cas:
  enabled: false
  prefixUrl: http://localhost:9000
  loginUrl: ${cas.prefixUrl}/login
  callbackUrl: http://localhost:${server.port}/callback
  logoutRedirect: http://localhost:${server.port}/swagger-ui.html

oauth2:
  enabled: true
  server: http://192.168.4.152:8090
  baseUrl: ${oauth2.server}/gateway/reception-center
  clientId: a1c7b4a4ade84e888009dcdad83909a1
  clientSecret: 8d28a7aef4af477a8da685a3afaa75d8
  accessTokenUri: ${oauth2.baseUrl}/oauth/token
  userAuthorizationUri: ${oauth2.baseUrl}/oauth/authorize
  profileUrl: ${oauth2.baseUrl}/member/who
  logoutUrl: ${oauth2.baseUrl}/member/logout
  logoutRedirect: ${oauth2.server}/auth_static/logout.html?redirect_uri=http://${eureka.instance.ip-address}:${server.port}/test&client_id=${oauth2.clientId}
  callbackUrl: http://${eureka.instance.ip-address}:${server.port}/callback

jwt:
  salt: ascs.tech

shiro:
  pathDefinitions:
    - /** = anon

minio:
  bucket: iform
  access:
    key:  icity
  secret:
    key: icity.ascs.tech
  host: http://192.168.4.151:9000 #存二维码图片的服务器地址（内网地址就可以了）
  url: http://192.168.4.151:9000 #二维码图片对应的地址前缀（如有必要需要变成外网地址）
  logoUrl: http://192.168.4.151:9000 #二维码中间商标 （内网地址就可以了）
  backUrl: http://192.168.4.151:9000 #二维码背景图 （内网地址就可以了）

multipart:
  maxFileSize: 10240Mb
  maxRequestSize: 10240Mb


logging:
  config: classpath:logback-boot.xml